### ISSUE TITLE
"learn" or "learn test"

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/learn-workflow-ide#3]
In part 5 there are a few textual references, and one visual reference, that students should use the command "learn" to run the a test. Then, the conclusion states students should use "learn test" to accomplish this. I will figure out which is correct when I run it, but these instructions are a little contradictory.

**Comment by AnnJohn** [comment]
hi @tripscripts both will work but you're right that the instructions can be confusing. We'll update.
