### ISSUE TITLE
A few items not specific to JS

### ISSUE THREAD

**Issue by mendelB** [learn-co-curriculum/learn-workflow-ide#4]
I know t'was mentioned that this will be customized for the JS course, raising these points just in case:

> We'll eventually introduce you to all of the Git mechanics that make this work.

Do we end up going over git in this course?

> All of the labs on Learn are written with an RSpec test suite...  RSpec is a testing library that ruby developers use everyday

I imagine we use a different test suite for this course?
Also the tests/pics/code examples in the rest of the Readme are all relevant to Ruby.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
